### ISSUE TITLE
[DOC]: Host user documentation using Github Pages

### ISSUE THREAD

**Issue by evan-palmer** [Robotic-Decision-Making-Lab/blue#31]
### Documentation Change Type

Adding new documentation to the BlueROV2 driver documentation

### Documentation Location

An initial version of the user documentation should be generated for the full project.

### Documentation Problem

There is currently no user documentation introducing the project or how to use it.

### Suggested Change

Create a user documentation website that describes how to use the project. If possible, it may be worth embedding the developer documentation into the site as well. However, if the theme of choice is not compatible with Doxygen, then the two should be kept separate.

**Comment by abubake** [comment]
Looking forward to seeing some great documentation with this project!

**Comment by evan-palmer** [comment]
This is *finally* in-progress. I made an orphan `gh-pages` branch that will be maintained separately from the `main` branch. I'll close this once I have an initial release ready and published.
